  # Dependencies
markdown:           redcarpet
redcarpet:
  extensions:       ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:        pygments

#github settings
baseurl:            /vpon-sdk
gem:

# Permalinks
permalink:          pretty

#Server
# host:               127.0.0.1
# port:               4000
# baseurl:            /
# url:                http://localhost:4000
# encoding:           UTF-8

# the excluded directoies
exclude:            []

# site information
info:
  site_name:        Vpon-SDK

meta:
  description:      "Here presents the simplist way to show ad"
  keywords:         "Default keywords for this site"
  author:           "Finn"

# multiple language
lang:          ["en", "zh-tw", "zh-cn", "jp"]

# left navigation
left_nav:
  en:
    title:          "Vpon SDK"
    path:           /vpon-sdk/
    # items:
    #   - path:       /page1
    #     title:      "Another page"
    #   - path:       /page2
    #     title:      "Yet another page"
  zh-tw:
    title:          "Vpon SDK"
    path:           /vpon-sdk/zh-tw

  zh-cn:
    title:          "Vpon SDK"
    path:           /vpon-sdk/zh-cn

  jp:
    title:          "Vpon SDK"
    path:           /vpon-sdk/jp


# right navigation
right_nav:
  - title:          English
    url:            /vpon-sdk/
    url1:           /vpon-sdk/android/
    url2:           /vpon-sdk/ios/
    url3:           /vpon-sdk/web/

  - title:          繁體中文
    url:            /vpon-sdk/zh-tw/
    url1:           /vpon-sdk/zh-tw/android/
    url2:           /vpon-sdk/zh-tw/ios/
    url3:           /vpon-sdk/zh-tw/web/

  - title:          简体中文
    url:            /vpon-sdk/zh-cn
    url1:           /vpon-sdk/zh-cn/android/
    url2:           /vpon-sdk/zh-cn/ios/
    url3:           /vpon-sdk/zh-cn/web/

  - title:          日本語
    url:            /vpon-sdk/jp
    url1:           /vpon-sdk/jp/android/
    url2:           /vpon-sdk/jp/ios/
    url3:           /vpon-sdk/jp/web/

# analytics account information, remember to change this.
analytics:
  google:
    account:         UA-43024238-5
