  # Dependencies
markdown:           redcarpet
redcarpet:
  extensions:       ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:        pygments

#github settings
baseurl:            /vpon-sdk
gem:

# Permalinks
permalink:          pretty

#Server
host:               127.0.0.1
port:               4000
baseurl:            /
url:                http://localhost:4000
encoding:           UTF-8

# the excluded directoies
exclude:            []

# site information
info:
  site_name:        Vpon-SDK

meta:
  description:      "Here presents the simplist way to show ad"
  keywords:         "Default keywords for this site"
  author:           "Finn"

# multiple language

languages:          ["en", "zh-tw", "zh-cn", "jp"]






# left navigation
left_nav:
  en:
    title:          "Vpon SDK"
    path:           /en
    # items:
    #   - path:       /page1
    #     title:      "Another page"
    #   - path:       /page2
    #     title:      "Yet another page"
  zh-tw:
    title:          "Vpon SDK"
    path:           /zh-tw
    # items:
    #   - path:       /zh-tw/page1
    #     title:      "頁面1"
    #   - path:       /zh-tw/page2
    #     title:      "頁面2"
  zh-cn:
    title:          "Vpon SDK"
    path:           /zh-cn
    # items:
    #   - path:       /zh-cn/page1
    #     title:      "页面1"
    #   - path:       /zh-cn/page2
    #     title:      "页面2"
  jp:
    title:          "Vpon SDK"
    path:           /jp
    # items:
    #   - path:       /jp/page1
    #     title:      "jp1"
    #   - path:       /jp/page2
    #     title:      "jp2"

# right navigation
right_nav:
  - title:          English
    url:            /
    url1:           /android/
    url2:           /ios/
    url3:           /web/

  - title:          繁體中文
    url:            /zh-tw/
    url1:           /zh-tw/android/
    url2:           /zh-tw/ios/
    url3:           /zh-tw/web/

  - title:          简体中文
    url:            /zh-cn
    url1:           /zh-cn/android/
    url2:           /zh-cn/ios/
    url3:           /zh-cn/web/

  - title:          日本語
    url:            /jp
    url1:           /jp/android/
    url2:           /jp/ios/
    url3:           /jp/web/

# analytics account information, remember to change this.
analytics:
  google:
    account:         UA-43024238-5
